### ISSUE TITLE
Organize documentation

### ISSUE THREAD

**Issue by lalmat** [lalmat/domoticz-api#10]
As the code is growing, we need to split the API documentation actually in the readme.md file into different sections of documentation.

It can be good to have a `docs` folder into the project and in this folder one markdown file by API entry :
- camera.md
- devices.md
- events.md
- notification.md
- scenes.md
- system.md

then, we can reference theses files into the readme.md

**Comment by AndrasBard** [comment]
Would you like to assign this issue to me?

**Comment by lalmat** [comment]
Done ! Thank you.
