### ISSUE TITLE
Make the dev/index less ugly without dependencies

### ISSUE THREAD

**Issue by lalmat** [lalmat/domoticz-api#3]
The dev/index.html is very ugly ATM. Maybe it can a little bit better visualy, but without dependencies.

**Comment by bensbits91** [comment]
Hi, I'd like to work on this. Do I need to be assigned, or can I just have at it? I've cloned, made a local branch, reviewed the code and taken a look at index.html. Seems like a fun issue. Thanks, Ben

**Comment by bensbits91** [comment]
I took a stab at some style, and created a pull request. Let me know if this is a good start, and if there's any changes you'd like me to make. If you don't like the style at all, I have some other ideas, so just let me know. Thanks, Ben

**Comment by bensbits91** [comment]
@lalmat [Here's my PR](https://github.com/lalmat/domoticz-api/pull/6). I hope it's okay that I submitted a PR without being assigned.

**Comment by lalmat** [comment]
Perfect ! Thank you @bensbits91 . It's merged !
